### ISSUE TITLE
Error when processing emails (move or copy)

### ISSUE THREAD

**Issue by PinkFloyd1213** [umanamente/n8n-nodes-imap#39]
Hello,

I am encountering a persistent error when using the `IMAP` node to move or copy emails. Here are the details of the error:

### **Error Details**
```
NodeApiError: Unable to move email, unknown error 
    at Object.executeImapAction (/home/node/.n8n/nodes/node_modules/n8n-nodes-imap/nodes/Imap/operations/email/functions/EmailMove.ts:55:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecuteContext.execute (/home/node/.n8n/nodes/node_modules/n8n-nodes-imap/nodes/Imap/Imap.node.ts:153:28)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:741:19)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:724:51
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1155:20
```

### **Additional Information**
- **Node Type**: `n8n-nodes-imap.imap`
- **Node Version**: 1 (Latest)
- **n8n Version**: 1.72.1 (Self Hosted)

### **What I’ve Checked**
- I’m using the correct plugin identifier, `n8n-nodes-imap`, and not the default n8n one.
- The workflow parameters appear to be configured correctly.

**Attachments**
Here are some screenshots of my workflow for reference.
![image_2024-12-26_110103493](https://github.com/user-attachments/assets/ba8afbf0-73ad-4108-a230-f203bb419176)
![image_2024-12-26_110209640](https://github.com/user-attachments/assets/cbedcfe2-cb60-4823-b04e-38d8ff26377c)

---

Thank you in advance for your assistance!

Best regards

**Comment by umanamente** [comment]
Unfortunately, the UID provided by the built-in IMAP Email Trigger node in N8n is not compatible with the IMAP node. To use the Move or Copy commands, you need the message ID that the IMAP service specifically returns for these commands. The built-in IMAP trigger does not support passing these parameters. To move emails, please first retrieve the list of emails using the IMAP node and then use the UID identifiers from that list.

**Comment by PinkFloyd1213** [comment]
Hello, 

Yes, I’m aware of that. I use the ID provided by your add-on. Please see the pictures here:  

![image](https://github.com/user-attachments/assets/f7c025ee-fdb6-4bfc-bc85-b87b025c874e)  
![image](https://github.com/user-attachments/assets/b271b146-771b-4620-ba26-c240adc72094)  

As I mentioned in my first message, I have already checked this, as it’s a common mistake.

**Comment by umanamente** [comment]
Please try using "**uid**" instead of "**id**"

**Comment by PinkFloyd1213** [comment]
Ooh ok, you mean this UID.. Not very clear, but it's working now. Thanks !
